"""
app/services/rubric_engine.py
-----------------------------
Structured Rubric Generation & Evaluation Engine for GetHire.
Generates reusable, category-weighted rubrics for interview questions
and computes rubric dimensional scores.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List

from app.models.interview import InterviewQuestion
from app.services.keyword_engine import KeywordMatchResult


@dataclass(frozen=True)
class QuestionRubric:
    """Configurable scoring criteria for a specific interview question."""
    category: str
    difficulty: str
    expected_concepts: List[str]
    required_keywords: List[str]
    optional_keywords: List[str]
    scoring_weights: Dict[str, float]  # weights sum to 1.0
    passing_threshold: int = 70


@dataclass
class RubricEvaluationResult:
    """Dimensional scores and feedback generated by rubric evaluation."""
    technical_accuracy_score: int
    concept_coverage_score: int
    problem_solving_score: int
    completeness_score: int

    technical_strengths: List[str] = field(default_factory=list)
    technical_weaknesses: List[str] = field(default_factory=list)
    technical_explanation: str = ""

    concept_strengths: List[str] = field(default_factory=list)
    concept_weaknesses: List[str] = field(default_factory=list)
    concept_explanation: str = ""

    problem_solving_strengths: List[str] = field(default_factory=list)
    problem_solving_weaknesses: List[str] = field(default_factory=list)
    problem_solving_explanation: str = ""

    completeness_strengths: List[str] = field(default_factory=list)
    completeness_weaknesses: List[str] = field(default_factory=list)
    completeness_explanation: str = ""


def build_rubric_for_question(question: InterviewQuestion) -> QuestionRubric:
    """
    Construct a tailored rubric blueprint based on question category and difficulty.
    """
    cat = question.category
    diff = question.difficulty.lower()

    # Base weights by category
    if cat == "Technical":
        weights = {"technical_accuracy": 0.40, "concept_coverage": 0.30, "problem_solving": 0.15, "communication": 0.10, "completeness": 0.05}
    elif cat == "Problem Solving":
        weights = {"problem_solving": 0.40, "technical_accuracy": 0.25, "concept_coverage": 0.20, "communication": 0.10, "completeness": 0.05}
    elif cat in ("Projects", "Resume-based"):
        weights = {"technical_accuracy": 0.30, "problem_solving": 0.25, "concept_coverage": 0.25, "communication": 0.10, "completeness": 0.10}
    elif cat == "Behavioral":
        weights = {"problem_solving": 0.35, "completeness": 0.25, "communication": 0.25, "concept_coverage": 0.10, "technical_accuracy": 0.05}
    else:
        weights = {"technical_accuracy": 0.30, "concept_coverage": 0.25, "problem_solving": 0.25, "communication": 0.10, "completeness": 0.10}

    threshold = 75 if diff == "hard" else (68 if diff == "medium" else 60)

    return QuestionRubric(
        category=cat,
        difficulty=question.difficulty,
        expected_concepts=question.expected_concepts or [f"Proficiency in {question.skill_targeted or 'core concepts'}"],
        required_keywords=[c.lower() for c in question.expected_concepts],
        optional_keywords=[(question.skill_targeted or "").lower()],
        scoring_weights=weights,
        passing_threshold=threshold,
    )


def evaluate_rubric(
    rubric: QuestionRubric,
    keyword_res: KeywordMatchResult,
    word_count: int,
) -> RubricEvaluationResult:
    """
    Compute dimensional scores using keyword coverage and response depth.
    """
    match_ratio = keyword_res.match_ratio

    # 1. Concept Coverage Score (0-100)
    concept_score = int(round(match_ratio * 100))
    concept_strengths = [f"Addressed '{c}'" for c in keyword_res.matched_concepts]
    concept_weaknesses = [f"Missed discussion on '{c}'" for c in keyword_res.missing_concepts]
    concept_exp = (
        f"Covered {len(keyword_res.matched_concepts)} of {len(rubric.expected_concepts)} expected key concepts."
    )

    # 2. Technical Accuracy Score (0-100)
    # Scales with concept coverage + penalty if very few keywords
    base_tech = match_ratio * 90 + (10 if keyword_res.raw_term_density > 0.04 else 0)
    if word_count < 15:
        base_tech = min(base_tech, 30)
    tech_score = int(round(min(100, max(0, base_tech))))

    tech_strengths = []
    tech_weaknesses = []
    if tech_score >= 80:
        tech_strengths.append("Strong technical terminology and accurate domain concepts")
    elif tech_score >= 50:
        tech_strengths.append("Basic technical principles correctly identified")
        tech_weaknesses.append("Could deepen technical precision and reference architectural mechanisms")
    else:
        tech_weaknesses.append("Answer lacks essential technical vocabulary and core architectural rigor")
    tech_exp = f"Technical accuracy graded at {tech_score}/100 based on domain terminology depth."

    # 3. Problem Solving Score (0-100)
    # Rewards reasoning depth & structure
    if word_count >= 30 and match_ratio >= 0.5:
        ps_score = min(100, int(round(match_ratio * 70 + 25)))
    elif word_count >= 15:
        ps_score = min(100, int(round(match_ratio * 60 + 20)))
    else:
        ps_score = min(100, int(round(match_ratio * 40 + 15)))

    ps_strengths = []
    ps_weaknesses = []
    if ps_score >= 75:
        ps_strengths.append("Clear problem breakdown with sound logical methodology")
    else:
        ps_weaknesses.append("Explain specific architectural tradeoffs and alternative design approaches")
    ps_exp = f"Problem-solving methodology scored at {ps_score}/100."

    # 4. Completeness Score (0-100)
    # Expected benchmark: 35-50 words for verbal responses
    target_words = 50 if rubric.difficulty.lower() == "hard" else 35
    depth_ratio = min(1.0, word_count / target_words)
    comp_score = int(round(min(100, (match_ratio * 0.6 + depth_ratio * 0.4) * 100)))

    comp_strengths = []
    comp_weaknesses = []
    if comp_score >= 75:
        comp_strengths.append("Comprehensive response addressing key dimensions")
    else:
        comp_weaknesses.append(f"Answer brevity ({word_count} words); aim for {target_words}+ words to fully flesh out reasoning")
    comp_exp = f"Answer completeness evaluated at {comp_score}/100."

    return RubricEvaluationResult(
        technical_accuracy_score=tech_score,
        concept_coverage_score=concept_score,
        problem_solving_score=ps_score,
        completeness_score=comp_score,
        technical_strengths=tech_strengths,
        technical_weaknesses=tech_weaknesses,
        technical_explanation=tech_exp,
        concept_strengths=concept_strengths,
        concept_weaknesses=concept_weaknesses,
        concept_explanation=concept_exp,
        problem_solving_strengths=ps_strengths,
        problem_solving_weaknesses=ps_weaknesses,
        problem_solving_explanation=ps_exp,
        completeness_strengths=comp_strengths,
        completeness_weaknesses=comp_weaknesses,
        completeness_explanation=comp_exp,
    )
